<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class User extends CI_Controller
{
	
	function __construct()
	{
		parent::__construct();
		$this->load->model("admin/Model_user");
		//BUAT MODEL USER//
	}

	//DISINI SEMUA YANG BERHUBUNGAN DENGAN INTERAKSI USER, SEPERTI LOGIN, DAFTAR USER DSB. login.php bisa dihapus :*
	public function login()
	{
		# code...
		$this->load->view("admin/login");
	}
	public function prosesLogin()
	{
		$username = $this->input->post('username');
		$password = $this->input->post('password');
		$cek = $this->Model_user->cek_login($username, $password);
		if($cek->num_rows() > 0){
			//session: how to use: $this->session->set_userdata('username', $var);
			$this->session->set_flashdata("success", "Sukses Login");
			$this->session->set_userdata("username", $username);
			redirect(base_url('admin/'));
			//PASS ADMINNYA ENCRYPT NDA? WKWKWKWKWK. DIKIRA NDA BISA LIAT WKWKWK YAA NEBAK DOANG. SUARANYA WKWKWWK. HALAH WKWKWK AKU BELOM TIDOR WOY WKWKWKWKW BESOK KAN AKU DIRUMAH, HOW? HOW? WHERE? WHEN? WHY? WHAT? 5W1H YEEE BISAA KWWKWK BISA....MMM..BELI TIGA KARNA NGANU...MMMM...YUK, PENGEN NDA? MAU DIAPAIN? DIBOBOINNYA GIMMANA? APANYA YG DIELUS? KEPALA APA? BADAN YG MANA? YG ATAS MANA? OOHH..BAWAH MANA? RAMBUT APA? YANG MANA? BAGIAN MANA? KOK IDUNG? MAU DI...IYA BESOK MALAM. JAM 9 SEINGATKU. JAM 10 MALAM YG DARI JOGJA - JKT. WKWKWK . MINGGU PAGI TENIS . MALAM MINGGU? MINGGU MALAM? DON'T KNOW. IBU KEKNYA JUGA KERJA. MUNGKIN SORE BARU KELUAR , KARNA KAN NUNGGU MAS BRIAN JUGA. NDA TAU, KADANG KERJA SAMPE SIANG GITU, JADI SOREAN BARU OTW JOGJA. IYAA BIASANYA DIRUMAH PAPI. KARNA MUNGKIN KLUAR GITU CUMA MAKAN, KMAREN DITAGIH UNTUK TRAKTIR MAKAN AJA . IYAA. SEPERTINYA IYAA. ENDAK TAU, ENDAK SEPERTINNYA, TOHH YOO MEH NGAPA DIRUMAH TEROS, MASA SAMPE JOGJA PUN NDA JALAN JALAN. IYAA SAMA KELUARGA, DAN AKU PUN PEN JUGA JALAN JALAN, MALAMNYA BARU FAM-TIME MUNGKIN. MINGGU PAGI TENNIS, SIANG SORE DONT KNOW. MAS BRIAN KADANG SORE PULANG KADANG MALAM. RENCANANYA ABIS TENNIS PEN KLUAR JUGA, AKUNYA SIH, DARIPADA STRESSS DIRUMAH MELE WKWKWKW . SEBENERNYA KANGEN ANGKRINGAN SAMA SAYANG HEHE..MALAM MINGGU, MAKANYA ITU, BINGUNG AKU, AKU LAGI MIKIR JUGA PEN MAKAN DIMANA SAMA KLUARGA WKWK BELUM TAU, PALA MUMIT HARI INI CASHBAC MAU MASUK QA TRUS "UAT" , TADI ABIS KELAR MIXED PURCHASE JUGA SOALNYA, LUM TAU SKEMA DARI QA TESTINGNYA GIMANA, SOALE KALO NEMU ERROR ATAU BUG GITU, PASTI KEK OMELAN EMAK-EMAK WKWK. BEDA SOALE, CASHBAC GA DAPAT DATA DUMMY DARI CASHBACNYA MISAL UDAH SELESAI REDEEM POIN GITU, KITA GA TAU UDAH BENERAN KE REDEEM KE AKUN TERSEBUT, PADAHAL MM... AKUN YG DIKASIH DAN API YG DIKASIH MASIH DEVELOP BELUM PRODUCTION, PO BILANG KLO MISAL TADA X CASHBAC PURCHASE NYA UDAH BERHASIL, MASUKIN AJA KE QA SIKAT, TAPI MASALAHNYA MISAL QA TAHAP SIT NYA YAA ITU TADI, REDEEM POIN BUKTINYA MANA, UDAH NAMBAH ATAU BELUM DI POIN CASHBACNYA. AKUN DEVELOP CUMA BISA LOCAL APALAGI API DEVELOP, GA BISA KEK REDEEM KE AKUN CASHBAC KU GITU, KALO PRODUCTION BARU BISA. QA ERROR, YAUDAH BENAHI, THEN, LUM TAU MAU DI DEPLOY KAPAN, KARNA KALO UDAH KE TAHAP DEPLOY MEANS BECOME PRODUCTION, LEMBUR SAMPE JAM SEGINIAN BISA JADI, IYAA DIKANTOR. JAM 1.58 AJA MASIH ADA YG NUNGGU SYSADMIN. YAA BISA BENAHI, CUMA KAN BARU DI KITANYA AJA DEVELOPER, BELUM TAU DI USER HEHE APALAGI DI SISI BISNISNYA, KITA CUMA IKUT PROSEDUR SR (SYSTEM REQUIREMENT). MASALAHNYA ADALAH, CASHBACNYA NDA SEPENUHNYA 100% KASIH SR KE KITA, TAPI DEVELOPER DIMINTA 100% KASIH "MAMPU" REDEEM POINNYA. PO UDAH BANYAK TANYA, SAMPE KADANG SAMBAT KE AKU KLO CASHBACNYA YOO LAMA BANGET KASIH FEEDBACK. IMAGE DAN T&C AJA BELUM ADA. YAASEBENERNYA KAMIS DIMINTA UDA SELESAI SAMA PO, JUMAT LEMPAR KE QA, MAKANYA TADI AKU BARU PULANG MEPET MAGHRIB LAGI, NYELESAIIN FORMAT PURCHASING BARU LAGI, ADA PEMBENAHAN TADA MAKANYA CASHBAC SEDIKIT IMPROVEMENT LAGI. TADA -> ACO, CASHBAC -> AKU, TADA UDAH LAMA RELEASE, UDAH MASUK QA, CUMA ADA TEMUAN YG CUMA BISA 1 JENIS ITEM, TRUS KMAREN DIBENAHI, LUMAYAN BANYAK, AKU HARUS NUNGGU SELESAI SEBELUM BISA COBA/TESTING DI JAVAKU SENDIRI DAN EMULATOR FE. SEBENERNYA SIHH GA SUSAH, CUMAN YAA ITU TADI, BUKTI HASIL REDEEMNYA KALAU BERHASIL, KAN HARUSNYA MASUK TUH, KITA GA DIKASIH DATA DUMMY DARI CASHBACNYA, JADI MINUSNYA KURANG TAU BENER2 BISA KE REDEEM NDA ITU POINNYA, KALO YG SELAMA INI AKU COBAIN, KEK GININIH SKEMANYA [PEMBELI MEMESAN CASHBAC POIN RP5000 DENGAN QTY 1, DITAMBAH CASHBAC POIN RP 25000 DENGAN QTY 1. RESULTPURCHASE?] BEGITU. TAPI PROSES DI BALIK ITU, PANJANG BANGET, 1. CEK TOTAL SIMASPOIN DULU, 2. PENGAMBILAN TOKEN DENGAN MENEMBAK API CASHBACNYA (DISINI SERING BANGET FAIL), 3. TEMBAK API INQUIRY CASHBAC UNTUK VALIDASI EMAIL (JIKA TOKEN SAAT LOGIN GAGAL, INI NDA DAPAT RESPON APA2), 4. TEMBAK API COMMIT CASHBAC UNTUK MENYIMPAN POINNYA (KALAU INQUIRY GAGAL, INI FAIL), 5. TEMBAK API SIMASPOIN UNTUK VALIDASI POIN LAGI, 6. TEMBAK API STOREVOUCHER UNTUK STORE VOUCHER2 YG SUDAH DIBELI APA AJA, 7. TEMBAK API SEND EMAIL PURCHASE EGIFT KE USER YG MEMBELI. QA CUMA TESTING PEMESANAN DENGAN MUNGIN STRESS TEST 1000 USER PURCHASE REDEEM POIN CASHBAC. WKWKWKW NULISKU NGEGAS, CAPS SEMUA YA ALLAH WKWKWKW. PELUK DONG, AUTO ISTIRAHAT WKWKWKW. BOLEH, PELUUK SE KAKI2NYA HEHE TRUS TANGAN SAYANG DI PIPI WKKW SUKA . SEMANGAT SAYANG SKRIPSIANNYA, MAAF MENGGANGGU TULISANKU YG GA GENAH INI WAKAKAKAKAKA SAMPE NULIS 7 API APAAN PULA INI. SUARA SAYANG BEGITU, AKU JADI SERASA NDA NGANTUK, SUKA HEHE. KLO LAGI DIJALAN GIMANA SUARANYA? WKWKW DIJALANAN TENGAH LAPANGAN, KEKMANA ? BUKTIKAN. YG BAGIAN MANA? MANA LUBANGNYA? NOTHING WKKWK JUST RANDOM WKWK OTAK RANDOM. SUKA YG RANDOM GAJE GINI? SEHAT GA ?
		}else{
			//redirect login
		}
	}

	public function logout()
	{
		$this->session->unset_userdata("username");
		$this->session->sess_destroy();
		redirect(base_url('admin/User/login'));
	}

	//dst
}